apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rhosp-whott-addtopics-notify
spec:
  schedule: "30 8 * * 4"
  successfulJobsHistoryLimit: 4
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
          - name: whott-topics-reminder
            image: nginx:alpine
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H 'Content-type: application/json' --data '{"type": "mrkdwn", "text":"

              :kubernetes::tekton::pipelines::technologist::point_right: *WHOTT! (Weekly Hour of Tekton & Tech)* :point_left::technologist::pipelines::tekton::kubernetes:


              <!subteam^S014X6HTR8U> :technologist: Please add topics here: https://docs.google.com/document/d/1-g_qU7OUtxk27yGdPOrQAgy9Nykt7RF1lu2gzfRqH9k/edit?usp=sharing

              :virtual-meeting: :point_right: https://meet.google.com/csu-owfi-hbm

              :mshourglass::mshourglass::mshourglass::mshourglass::mshourglass:

              🇫🇷  *Paris*      : Thursday *12:30:00 PM* CEST
              🇺🇸  *Boston*     : Thursday *06:30:00 AM* EDT
              🇦🇺  *Brisbane* : Thursday *08:30:00 PM* AEST
              🇮🇳  *Bangalore*  : Thursday *04:00:00 PM* IST
              🐻  *California* : Thursday *03:30:00 AM* PDT

              "}' $(cat /data/url)
            volumeMounts:
              - mountPath: /data
                name: webhook-url
          restartPolicy: OnFailure
          volumes:
            - name: webhook-url
              secret:
                secretName: coreos-tektondev-webhook