apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rhosp-standup-notify
spec:
  schedule: "25 12 * * 1-4"
  successfulJobsHistoryLimit: 4
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
          - name: trigger-pipeline
            image: nginx:alpine
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              curl -X POST -H 'Content-type: application/json' --data '{"type": "mrkdwn", "text":":pipelines::tekton::loud_sound: <!subteam^S014X6HTR8U>

              *RHOSP Daily Standup*

              :virtual-meeting: :point_right: https://meet.google.com/zsy-qgby-xdu


              :mshourglass::mshourglass::mshourglass::mshourglass::mshourglass:

              🇫🇷  Paris      : 02:30:00 PM CEST 2021
              🇺🇸  Boston     : 08:30:00 AM EDT 2021
              🇮🇳  Bangalore  : 06:00:00 PM IST 2021
              🐻  California : 05:30:00 AM PDT 2021

              "}' $(cat /data/url)
            volumeMounts:
              - mountPath: /data
                name: webhook-url
          restartPolicy: OnFailure
          volumes:
            - name: webhook-url
              secret:
                secretName: coreos-tektondev-webhook