---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: notify-release-milestones
spec:
  params:
  - name: releaseDataFile
    default: "rhosp-release-latest.yaml"
    description: name of the file which has date on release milestones
  workspaces:
  - name: release-milestones
    description: configMap which has releaseDataFile
  - name: workarea
  results:
  - name: release-milestones-notification
    description: copy of the notification send to slack
    value: $(tasks.generate-release-milestones-message.results.milestones)
  tasks:
  - name: generate-release-milestones-message
    taskRef:
      name: generate-release-milestones
    params:
    - name:  releaseDataFile
      value: $(params.releaseDataFile)
    workspaces:
    - name: release-milestones
      workspace: release-milestones
    - name: output
      workspace: workarea
  - name: slack-message
    taskRef:
      name: send-to-webhook-slack
    params:
    - name: bot-name
      value: iBuildCaptainBot
    - name: icon-emoji
      value: ':technologist:'
    - name: message
      value: $(tasks.generate-release-milestones-message.results.milestones)
    - name: webhook-secret
      value: coreos-webhook-tekton-dev
